#!/bin/bash

URL="http://localhost:3000/api"
FILES="${URL}/files"
TAGS="${URL}/tags"
GET="curl -Ss"
PUT="curl -Ss -X PUT -H Content-Type:application/json"
POST="curl -Ss -X POST -H Content-Type:application/json"

file="$1"
once="$2"

windowid=$(xdotool search  --class feh)

tagsfile=$(mktemp)
filesfile=$(mktemp)
$GET $TAGS  | jq -r '.result[]|"\(.id),\(.name)"' > $tagsfile
$GET $FILES | jq -r '.result[]|"\(.id),\(.name)"' > $filesfile
this_id=$(grep ",${file}$" "$filesfile" | cut -d, -f1)

while true; do
  added=$(cut -d, -f2- $tagsfile | dmenu ${windowid:+-w $windowid} \
    -f -l 5 -p 'add tag > ')
  if [[ -z "$added" ]] ; then
    break;
  fi

  added_id=$(grep ",${added}$" $tagsfile | cut -d, -f1)
  if [[ -z $added_id ]]; then
    data=$(jq -c --null-input --arg name "$added" '{"name": $name}')
    newtag=$($POST $TAGS --data "$data")
    echo "created new tag ${newtag}"
    added_id=$(printf '%s' "$newtag" | jq -r '.result.id')
  fi

  existing=$($GET "${FILES}/${this_id}" | jq -r '.result')
  data=$(printf '%s' "$existing" | jq -c \
    --argjson added "$added_id" \
    '.Tags = (.Tags|[.[].id] + [$added])')

  $PUT "${FILES}/${this_id}" --data "$data" >/dev/null
  if [[ -n $once ]]; then
    break
  fi
done
